import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Aside from '@/components/Aside/Aside'
import AddMessage from '@/components/AddMessage/AddMessage'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Aside />
    <section className= {styles.container}>
<AddMessage />
    </section>

      </main>
    </>
  )
}
